import { LegalArea } from './document.types';

export enum ArticleStatus {
  DRAFT = 'DRAFT',
  IN_REVIEW = 'IN_REVIEW',
  READY_TO_PUBLISH = 'READY_TO_PUBLISH',
  SCHEDULED = 'SCHEDULED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED'
}

export enum PublicationSection {
  ACTUALIZACIONES_NORMATIVAS = 'ACTUALIZACIONES_NORMATIVAS',
  JURISPRUDENCIA = 'JURISPRUDENCIA',
  ANALISIS_PRACTICO = 'ANALISIS_PRACTICO',
  DOCTRINA = 'DOCTRINA',
  MAS_RECIENTES = 'MAS_RECIENTES'
}

export enum GenerationTone {
  PROFESSIONAL = 'PROFESSIONAL',
  ACADEMIC = 'ACADEMIC',
  ACCESSIBLE = 'ACCESSIBLE'
}

export interface AIGenerationConfig {
  targetLength: number;
  tone: GenerationTone;
  focusAreas: string[];
  includePracticalExamples: boolean;
  citationStyle: 'academica' | 'profesional' | 'simplificada';
}

export interface AIGenerationMetadata {
  section: string;
  generatedAt: string;
  modelUsed: string;
  confidenceScore: number;
  promptUsed: string;
  userEdited: boolean;
}

export interface Article {
  id: string;
  sourceDocumentId: string;
  
  // Content
  title: string;
  slug: string;
  content: string;
  summary: string;
  
  // SEO
  seoTitle?: string;
  metaDescription?: string;
  keywords: string[];
  canonicalUrl?: string;
  
  // Categorization
  legalArea: LegalArea;
  publicationSection: PublicationSection;
  tags: string[];
  
  // Editorial Status
  status: ArticleStatus;
  authorId: string;
  editorId?: string;
  
  // Publication
  scheduledPublication?: string;
  publishedAt?: string;
  
  // Metrics
  wordCount: number;
  readingTime: number;
  viewCount?: number;
  engagementScore?: number;
  
  // AI Metadata
  aiGeneratedSections: AIGenerationMetadata[];
  generationParameters?: AIGenerationConfig;
  
  // Timestamps
  createdAt: string;
  updatedAt: string;
  lastEditedAt: string;
}

export interface ArticleVersion {
  id: string;
  articleId: string;
  versionNumber: number;
  label?: string;
  
  // Version Content
  title: string;
  content: string;
  summary: string;
  seoTitle?: string;
  metaDescription?: string;
  
  // Metadata
  createdById: string;
  autoGenerated: boolean;
  changeSummary?: string;
  wordCountDelta: number;
  
  // Timestamps
  createdAt: string;
}

export interface ArticleFilters {
  page?: number;
  limit?: number;
  status?: ArticleStatus;
  author?: string;
  legalArea?: LegalArea;
  publicationSection?: PublicationSection;
  createdAfter?: string;
  search?: string;
}

export interface ArticleCreateRequest {
  sourceDocumentId: string;
  title: string;
  targetLength?: number;
  tone?: GenerationTone;
  focusAreas?: string[];
}

export interface ArticleUpdateRequest {
  title?: string;
  content?: string;
  summary?: string;
  keywords?: string[];
  seoTitle?: string;
  metaDescription?: string;
  legalArea?: LegalArea;
  publicationSection?: PublicationSection;
  tags?: string[];
}